"""application constants"""

import sys
import os

ROOT_HEIGHT = 650
ROOT_WIDTH = 500
ROOT_TITLE = "HK Salary Calculator"
NAME_COLUMN_HEADER = "Name"
SALARY_COLUMN_HEADER = "Salary"
TYPE_COLUMN_HEADER = "Type"
NAME_COLUMN_WIDTH = 230
SALARY_COLUMN_WIDTH = 100
TYPE_COLUMN_WIDTH = 100
DEFAULT_BUTTON_SIZE = 20
ATTACH_LABEL_SIZE = 200
ATTACH_BUTTON_TEXT = "Attach Attendance Sheet"
CALC_AND_SAVE_BUTTON_TEXT = "Calculate & Save"
DEFAULT_BUTTON_Y_PADDING = (100, 0)
ATTACH_LABEL_Y_PADDING = (0, 100)
DARK_GREEN = "#263D42"
WHITE = "white"
ATTACH_ATTENDANCE_SHEET_MSG = "Please Attach Attendance Sheet"
SAVED_MSG = "Saved!"
DEFAULT_LABEL_TEXT = ""
EDIT_ENTRY_SAVE_BUTTON = "Save"
EDIT_WIN_TITLE = "Edit Entry"
EDIT_ENTRY_NAME_LABEL_TEXT = "Name: "
EDIT_ENTRY_SAVE_LABEL_TEXT = "Salary: "
EDIT_ENTRY_TYPE_LABEL_TEXT = "Type: "
ROW_DIFF_FOR_EMP_NAME = 6
ROW_DIFF_FOR_ATTEN_STATS = 1
COL_FOR_ATTEN_STATS = 1
DAY_STATS_PATTERN = "\\d+.{0,1}\\d*"
DURATION_STAT_PATTERN = "[\\d]*[:;][\\d]*"
OPERATOR_TYPE = "OPERATOR"
REGULAR_TYPE = "REGULAR"
DRIVER_TYPE = "DRIVER"
APP_NAME = "/app"
PATH_TO_EXE = sys.executable.replace(APP_NAME, "")
APP_DATA_FILE_NAME = "salary.json"
if hasattr(sys, "frozen"):
    SALARY_FILE_PATH = os.path.join(PATH_TO_EXE, APP_DATA_FILE_NAME)
else:
    SALARY_FILE_PATH = APP_DATA_FILE_NAME
DEFAULT_SHEET_NAME = "Calculated Salaries"
BACKSPACE_KEYSYM = "BackSpace"
